SET
FOREIGN_KEY_CHECKS = 0;

TRUNCATE TABLE order_item;
TRUNCATE TABLE `order`;
TRUNCATE TABLE user_point_lot;
TRUNCATE TABLE point_policy;
TRUNCATE TABLE product;
TRUNCATE TABLE `user`;

SET
FOREIGN_KEY_CHECKS = 1;